"""
Provides functionality for executing code within a sandboxed environment using Firejail.

This module defines the `CodeRunner` class, which is responsible for constructing
and running commands within a Firejail sandbox to securely execute code from
Devika-generated projects. It handles subprocess management, output capturing,
and error reporting.
"""

import os
import subprocess
from typing import List, Optional, TypedDict

from src.config import Config
from src.logger import Logger

logger = Logger()
config = Config() # Module-level Config instance

# Default Firejail profile - consider making this configurable or more specific
# For a very restrictive environment, a custom profile is recommended.
# Example: "/etc/firejail/default.profile" or a custom one like "/etc/firejail/devika.profile"
# DEFAULT_FIREJAIL_PROFILE_NAME = "default.profile" # Will be handled by config or argument
FIREJAIL_EXECUTABLE = config.get_firejail_executable_path()


class CodeExecutionResult(TypedDict):
    """
    Represents the result of a sandboxed code execution.

    Attributes:
        stdout (str): The standard output from the executed command.
        stderr (str): The standard error output from the executed command.
        return_code (int): The return code of the executed command.
        success (bool): True if the command executed successfully (return code 0), False otherwise.
        error_message (Optional[str]): An additional error message if execution failed at
                                     the subprocess level (e.g., timeout, Firejail not found).
    """

    stdout: str
    stderr: str
    return_code: int
    success: bool
    error_message: Optional[str]


class CodeRunner:
    """
    Executes code within a Firejail sandbox.

    This class constructs Firejail commands to run project code in a restricted
    environment, captures its output, and handles basic error reporting.

    Security Note:
        This class relies on Firejail for sandboxing. The effectiveness of the sandbox
        depends heavily on the Firejail installation, configuration, and the profiles used.
        It is crucial that Firejail is set up correctly and that appropriate, restrictive
        profiles are used. Commands executed are assumed to be generated by an LLM
        that has been prompted for safe and relevant operations. No additional validation
        on the commands themselves (beyond what the LLM provides) is performed by this class.
        The project directory is mounted read-only by default in the sandbox. Network
        access should ideally be disabled or severely restricted by the Firejail profile.

    Attributes:
        firejail_profile_path (Optional[str]): Path to a specific Firejail profile to use.
                                            If None, Firejail's default behavior applies.
        config (Config): Application configuration instance.
    """

    def __init__(self, firejail_profile_path_arg: Optional[str] = None) -> None:
        """
        Initialize the CodeRunner.

        Args:
            firejail_profile_path_arg (Optional[str]): Path to a custom Firejail profile.
                                                       If None, it attempts to use the path
                                                       from `config.get_firejail_default_profile_path()`.
                                                       If that's also None/empty, Firejail's
                                                       default behavior or internal restrictive
                                                       options will apply.
        """
        self.config: Config = Config() # Instance config for other methods if needed
        
        effective_profile_path = firejail_profile_path_arg
        if effective_profile_path is None:
            effective_profile_path = self.config.get_firejail_default_profile_path()
        
        self.firejail_profile_path: Optional[str] = effective_profile_path

        # Simple check if firejail command seems available
        try:
            subprocess.run(
                [FIREJAIL_EXECUTABLE, "--version"], capture_output=True, check=False
            )
            logger.info(
                f"CodeRunner initialized. Firejail executable found. Profile: {self.firejail_profile_path or 'Firejail default/restrictive fallback'}"
            )
        except FileNotFoundError:
            logger.error(
                f"Firejail executable '{FIREJAIL_EXECUTABLE}' not found. "
                "Code execution will not be sandboxed properly. Please install Firejail."
            )
            # Depending on policy, could raise an error here.
    
    # Removed DEFAULT_FIREJAIL_PROFILE_NAME as its logic is now incorporated
    # into __init__ and _construct_firejail_command through self.firejail_profile_path

    def _construct_firejail_command(
        self, project_code_path_host: str, command_to_run_in_sandbox: List[str]
    ) -> List[str]:
        """
        Construct the full Firejail command list for execution.

        Args:
            project_code_path_host (str): The absolute path to the project's code
                                          directory on the host machine. This directory
                                          will be made available inside the sandbox.
            command_to_run_in_sandbox (List[str]): The actual command and its arguments
                                                   to execute inside the sandbox
                                                   (e.g., ["python", "main.py"]).

        Returns:
            List[str]: The fully constructed command list suitable for `subprocess.run()`.

        Notes on Firejail options used:
            --quiet: Suppress Firejail's own startup messages.
            --noprofile: Starts with a very minimal profile (essentially empty).
                         This is good for building up a profile from scratch.
                         If a general restrictive profile is desired as a base,
                         this could be omitted and rely on /etc/firejail/default.profile
                         or a specified profile.
            --read-only=${project_code_path_host}: Mounts the project directory read-only
                                                   into the sandbox at the same path.
            --whitelist=${project_code_path_host}: Ensures the project path is accessible.
            --private: Creates a minimal temporary home directory.
            --private-tmp: Mounts a new, empty /tmp.
            --private-dev: Creates a minimal /dev.
            --net=none: Disables network access. Critical for untrusted code.
            --caps.drop=all: Drops all Linux capabilities.
            --seccomp: Enables seccomp-bpf filter for syscall blocking.
                       Requires a kernel with seccomp support.
            --nogroups: Disables supplementary groups.
            --nonewprivs: Ensures the process cannot gain new privileges.
            --noroot: Disables root privileges (user namespace).
            --hostname=devika-sandbox: Sets a custom hostname inside the sandbox.
            -- PWD=${project_code_path_host}: Sets the working directory inside sandbox.
               Firejail typically changes CWD to the first whitelisted path or /home/user.
               This ensures commands are run from the project's root.
        """
        firejail_command: List[str] = [FIREJAIL_EXECUTABLE]

        # Apply a specific profile if provided and exists
        if self.firejail_profile_path and os.path.exists(self.firejail_profile_path):
            firejail_command.extend([f"--profile={self.firejail_profile_path}"])
        elif self.firejail_profile_path:  # Profile specified but not found
            logger.warning(
                f"Specified Firejail profile '{self.firejail_profile_path}' not found. "
                "Applying default restrictive options instead."
            )
            # Apply a restrictive set of options if a custom profile is missing
            firejail_command.extend(
                [
                    "--quiet",
                    "--noprofile",  # Start clean if specific profile is missing
                    f"--read-only={project_code_path_host}",
                    f"--whitelist={project_code_path_host}",
                    "--private",  # Minimal /home
                    "--private-tmp",
                    "--private-dev",
                    "--net=none",
                    "--caps.drop=all",
                    "--seccomp",
                    "--nogroups",
                    "--nonewprivs",
                    "--noroot",
                ]
            )
        else:  # No custom profile specified, use a sensible default restrictive set
            logger.info(
                "No custom Firejail profile specified, applying default restrictive options."
            )
            firejail_command.extend(
                [
                    "--quiet",
                    "--noprofile",
                    f"--read-only={project_code_path_host}",
                    f"--whitelist={project_code_path_host}",
                    "--private",
                    "--private-tmp",
                    "--private-dev",
                    "--net=none",
                    "--caps.drop=all",
                    "--seccomp",
                    "--nogroups",
                    "--nonewprivs",
                    "--noroot",
                ]
            )

        firejail_command.append("--hostname=devika-sandbox")
        # Set working directory inside sandbox to be the project path
        firejail_command.append(f"--pwd={project_code_path_host}")
        firejail_command.extend(command_to_run_in_sandbox)

        return firejail_command

    def execute_code(
        self,
        project_name: str,
        command_to_run: List[str],
        timeout_seconds: int = 300,
    ) -> CodeExecutionResult:
        """
        Execute the given command for a project within a Firejail sandbox.

        Args:
            project_name (str): The name of the project. The actual directory path
                                will be derived from this.
            command_to_run (List[str]): The command and its arguments to execute
                                        (e.g., ["python", "main.py"]).
            timeout_seconds (int): Maximum time in seconds to allow the command to run.
                                   Defaults to 300 seconds (5 minutes).

        Returns:
            CodeExecutionResult: A dictionary containing the execution output,
                                 return code, success status, and any error messages.
        """
        project_slug = project_name.lower().replace(" ", "-")
        project_code_path_host = os.path.join(
            self.config.get_projects_dir(), project_slug
        )

        if not os.path.isdir(project_code_path_host):
            err_msg = f"Project directory for '{project_name}' not found at: {project_code_path_host}"
            logger.error(err_msg)
            return CodeExecutionResult(
                stdout="",
                stderr=err_msg,
                return_code=-1,
                success=False,
                error_message="Project directory not found",
            )

        if not command_to_run:
            logger.error("No command provided to execute_code.")
            return CodeExecutionResult(
                stdout="",
                stderr="No command provided.",
                return_code=-1,
                success=False,
                error_message="No command provided",
            )

        firejail_full_command = self._construct_firejail_command(
            project_code_path_host, command_to_run
        )
        logger.info(f"Executing sandboxed command: {' '.join(firejail_full_command)}")

        try:
            process = subprocess.run(
                firejail_full_command,
                capture_output=True,
                timeout=timeout_seconds,
                # `cwd` for subprocess.run itself is less critical if Firejail's --pwd handles it,
                # but setting it to project_path_host can be a fallback.
                # However, Firejail's --pwd should make the internal CWD correct.
                check=False,  # Do not raise CalledProcessError for non-zero exit codes
            )
            stdout = process.stdout.decode("utf-8", errors="replace")
            stderr = process.stderr.decode("utf-8", errors="replace")
            return_code = process.returncode
            success = return_code == 0

            log_func = logger.info if success else logger.warning
            log_func(
                f"Command executed. Return code: {return_code}. Success: {success}."
            )
            if stdout:
                logger.debug(f"Stdout:\n{stdout}")
            if stderr and not success:
                logger.warning(f"Stderr:\n{stderr}")
            elif stderr:
                logger.debug(
                    f"Stderr (command succeeded but stderr not empty):\n{stderr}"
                )

            return CodeExecutionResult(
                stdout=stdout,
                stderr=stderr,
                return_code=return_code,
                success=success,
                error_message=None,
            )
        except subprocess.TimeoutExpired:
            timeout_msg = f"Command timed out after {timeout_seconds} seconds: {' '.join(command_to_run)}"
            logger.warning(timeout_msg)
            return CodeExecutionResult(
                stdout="",
                stderr=timeout_msg,
                return_code=-1,  # Using -1 for timeout
                success=False,
                error_message="TimeoutExpired",
            )
        except FileNotFoundError:
            fnf_msg = (
                f"Firejail executable not found at '{FIREJAIL_EXECUTABLE}'. "
                "Please ensure Firejail is installed and in PATH."
            )
            logger.error(fnf_msg)
            return CodeExecutionResult(
                stdout="",
                stderr=fnf_msg,
                return_code=-1,
                success=False,
                error_message="Firejail not found",
            )
        except Exception as e:
            error_msg = f"An unexpected error occurred during code execution: {e}"
            logger.error(error_msg, exc_info=True)
            return CodeExecutionResult(
                stdout="",
                stderr=str(e),
                return_code=-1,  # Generic error code
                success=False,
                error_message=f"Unexpected error: {type(e).__name__}",
            )


if __name__ == "__main__":
    # This example block is for direct testing of this script.
    # It assumes a project "test-project-runner" exists in your configured projects directory.
    # You would need to create this directory and a sample file for testing.
    # e.g., projects/test-project-runner/test.py containing:
    #   import os
    #   print("Hello from sandboxed Python!")
    #   print(f"Current working directory in sandbox: {os.getcwd()}")
    #   # The following line will likely fail due to Firejail's default restrictions
    #   # print(f"Files in /: {os.listdir('/')}")
    #   # To test stderr:
    #   # import sys
    #   # sys.stderr.write("This is a test error message\\n")
    #   # sys.exit(1)

    logger.info("Starting CodeRunner example execution...")

    # Initialize with a default restrictive profile (or specify a custom one)
    # For this example, we'll rely on the default options in _construct_firejail_command
    # if no profile path is given or if the default profile name isn't found at a standard path.
    runner = CodeRunner()

    project_name_main = "test-project-runner"

    # Ensure the project directory and test file exist
    config_main = Config()
    project_dir_main = os.path.join(
        config_main.get_projects_dir(), project_name_main.lower().replace(" ", "-")
    )
    if not os.path.exists(project_dir_main):
        os.makedirs(project_dir_main, exist_ok=True)
        logger.info(f"Created test project directory: {project_dir_main}")

    test_file_path = os.path.join(project_dir_main, "test.py")
    if not os.path.exists(test_file_path):
        with open(test_file_path, "w", encoding="utf-8") as f:
            f.write('import os\nimport sys\nprint("Hello from sandboxed Python!")\n')
            f.write('print(f"Current working directory in sandbox: {os.getcwd()}")\n')
            # The following line might be restricted by Firejail depending on the profile
            # f.write('try:\n    print(f"Files in /: {os.listdir(\'/\')}")\nexcept Exception as e:\n    print(f"Could not list /: {e}")\n')
            # f.write('sys.stderr.write("This is a test error message to stderr\\n")\n')
            # f.write('sys.exit(0)\n') # Change to 1 to test error code
        logger.info(f"Created test file at {test_file_path}")

    execution_command_main = ["python3", "test.py"]
    result_main = runner.execute_code(
        project_name_main, execution_command_main, timeout_seconds=10
    )

    logger.info("\n--- Main Execution Result ---")
    logger.info(f"Success: {result_main['success']}")
    logger.info(f"Return Code: {result_main['return_code']}")
    logger.info(f"Stdout:\n{result_main['stdout']}")
    logger.info(f"Stderr:\n{result_main['stderr']}")
    if result_main["error_message"]:
        logger.info(f"Error Message: {result_main['error_message']}")

    # Example with a non-existent command (should result in error in stderr from shell inside Firejail)
    # result_error_command = runner.execute_code(project_name_main, ["nonexistentcommand123xyz"], timeout_seconds=5)
    # logger.info("\n--- Non-existent Command Execution Result ---")
    # logger.info(f"Success: {result_error_command['success']}")
    # logger.info(f"Return Code: {result_error_command['return_code']}")
    # logger.info(f"Stdout:\n{result_error_command['stdout']}")
    # logger.info(f"Stderr:\n{result_error_command['stderr']}")
    # if result_error_command['error_message']:
    #     logger.info(f"Error Message: {result_error_command['error_message']}")

    # Optional: Cleanup the created test project directory and file
    # import shutil
    # if os.path.exists(project_dir_main):
    #     shutil.rmtree(project_dir_main)
    #     logger.info(f"Cleaned up test project directory: {project_dir_main}")
    logger.info("CodeRunner example execution finished.")
